# Generated by Django 4.2.2 on 2023-06-21 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('owner', models.CharField(blank=True, max_length=30, null=True)),
                ('ownerNumber', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('captain', models.CharField(max_length=30)),
                ('captainNumber', models.CharField(max_length=15)),
                ('owner', models.CharField(max_length=30)),
                ('ownerNumber', models.CharField(max_length=15)),
                ('sourcePort', models.CharField(blank=True, max_length=30, null=True)),
                ('sourceDestination', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('agenty', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('file', models.FileField(upload_to='vessels/')),
                ('launch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.launch')),
            ],
        ),
    ]
