# Generated by Django 4.2.2 on 2023-06-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_usr_user_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vessel',
            old_name='sourceDestination',
            new_name='DestinationPort',
        ),
    ]
