# Generated by Django 4.2.2 on 2023-06-26 14:39

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_vesselparking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.generate_file_path),
        ),
        migrations.AlterField(
            model_name='vesselparking',
            name='days',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
