# Generated by Django 4.2.2 on 2023-07-07 11:22

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_vessel_file_userreceiveaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='mathrahani',
            field=models.FileField(blank=True, null=True, upload_to=api.models.mathrahani_file),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.generate_file_path),
        ),
    ]
