# Generated by Django 4.2.2 on 2023-07-31 14:07

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_vessel_mathrahani_alter_vessel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='number',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.generate_file_path),
        ),
    ]
