# Generated by Django 4.2.2 on 2023-08-06 13:31

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_vessel_exitreport_alter_vessel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='Warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='launch',
            name='note',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vessel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.generate_file_path),
        ),
    ]
