# Generated by Django 4.2.2 on 2023-08-06 14:06

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_vessel_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='launch',
            old_name='Warning',
            new_name='warning',
        ),
        migrations.AlterField(
            model_name='vessel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.generate_file_path),
        ),
    ]
