# Generated by Django 4.2.2 on 2023-08-06 14:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_warning_launch_warning_alter_vessel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.generate_file_path),
        ),
    ]
