# Generated by Django 4.2.2 on 2023-08-06 20:06

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_vessel_file_vesseldiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='vesseldiscount',
            name='vessel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.vessel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vessel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.generate_file_path),
        ),
    ]
