# Generated by Django 4.2.2 on 2023-08-06 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_vessel_file'),
        ('api', '0028_vesseldiscount_vessel_alter_vessel_file'),
    ]

    operations = [
    ]
