# Generated by Django 4.2.2 on 2023-08-11 10:39

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_userexpenseaccount_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vesselbooking',
            name='company',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.generate_file_path),
        ),
    ]
