# Generated by Django 4.2.2 on 2023-08-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_vesselbooking_amount_paid_vesselbooking_final_stamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesselbooking',
            name='pay_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
