# Generated by Django 4.2.2 on 2023-08-17 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_vesselbooking_pay_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vesselbooking',
            name='price',
        ),
    ]
