# Generated by Django 4.2.2 on 2023-08-23 09:25

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_vesselbooking_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesselaccount',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.vessel_file_path),
        ),
        migrations.AlterField(
            model_name='vesselamend',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.vessel_file_path),
        ),
        migrations.AlterField(
            model_name='vesselattestation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.vessel_file_path),
        ),
        migrations.AlterField(
            model_name='vesseldiscount',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.vessel_file_path),
        ),
        migrations.AlterField(
            model_name='vesselexit',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.vessel_file_path),
        ),
        migrations.AlterField(
            model_name='vesselexpenses',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.vessel_file_path),
        ),
        migrations.AlterField(
            model_name='vesselhamali',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.vessel_file_path),
        ),
        migrations.AlterField(
            model_name='vesselmanifest',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.vessel_file_path),
        ),
        migrations.AlterField(
            model_name='vesselparking',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.vessel_file_path),
        ),
        migrations.AlterField(
            model_name='vesseltruecopy',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.vessel_file_path),
        ),
    ]
