# Generated by Django 4.2.2 on 2023-08-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_vesselaccount_file_alter_vesselamend_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usr',
            name='daily_report',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
