# Generated by Django 4.2.2 on 2023-08-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_usr_daily_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='vesselhamali',
            name='extra_expense',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
