# Generated by Django 4.2.2 on 2023-08-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_vesselhamali_extra_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='exit_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
