# Generated by Django 4.2.2 on 2023-08-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_vessel_exit_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='usr',
            name='vessel_exit_report',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
