# Generated by Django 4.2.2 on 2023-08-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_usr_vessel_exit_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='exit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
